name: Package and Release

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Release package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install modular
        run: |
          curl -s https://get.modular.com | sh -
          modular auth examples

      - name: Install Mojo
        run: modular install mojo

      - name: Add to PATH
        run: echo "/home/runner/.modular/pkg/packages.modular.com_mojo/bin" >> $GITHUB_PATH

      - name: Create package
        run: mojo package toybox -o toybox.mojopkg

      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          # note: token is date-limited and restricted to appropriate repositories
          # and permissions required by the workflow
          # ref: https://github.com/svenstaro/upload-release-action
          repo_token: ${{ secrets.TOKEN_TO_PUBLISH_MOJOPKG_VIA_WORKFLOW }}
          file: toybox.mojopkg
          tag: latest-build
          overwrite: true